#!/bin/bash

echo "=== Yat_Casched 调度器基本测试指南 ==="
echo ""

echo "🔍 1. 检查调度器是否正确加载："
echo "在虚拟机终端中运行："
echo "   cat /proc/version"
echo "   dmesg | grep yat_casched"
echo ""

echo "📊 2. 查看系统基本信息："
echo "   ps aux              # 查看进程列表"
echo "   top                 # 系统监控"
echo "   uptime              # 运行时间"
echo "   free                # 内存使用"
echo ""

echo "⚡ 3. 简单性能测试："
echo "在虚拟机中创建一些负载来测试调度器："
echo ""
echo "# 创建 CPU 密集型任务"
echo "for i in \$(seq 1 4); do"
echo "  (while true; do echo \$i > /dev/null; done) &"
echo "done"
echo ""
echo "# 观察进程调度"
echo "ps aux"
echo "top"
echo ""
echo "# 停止后台任务"
echo "killall sh"
echo ""

echo "🧪 4. 缓存感知测试（手动）："
echo "# 创建内存访问测试"
echo "dd if=/dev/zero of=/tmp/test1 bs=1M count=10"
echo "dd if=/dev/zero of=/tmp/test2 bs=1M count=10"
echo "# 同时读取文件测试缓存"
echo "cat /tmp/test1 > /dev/null &"
echo "cat /tmp/test2 > /dev/null &"
echo "ps aux"
echo ""

echo "📝 5. 查看调度器统计信息："
echo "   cat /proc/schedstat  # 调度统计"
echo "   cat /proc/loadavg    # 负载平均"
echo ""

echo "💡 提示："
echo "- 所有命令都在 QEMU 虚拟机的终端中运行"
echo "- 要退出虚拟机: 输入 'exit'，然后按 Ctrl+A 再按 X"
echo "- 观察调度器行为时注意进程的 CPU 使用率分布"
